services:
  zmeta-web:
    build:
      context: .
      args:
        VITE_MODE: staging
        VITE_API_BASE_URL: ""
    container_name: zmeta-web
    ports:
      - "3010:80"
    environment:
      BACKEND_URL: http://zmeta-core:8087
    networks:
      - zmeta-net
    restart: unless-stopped

networks:
  zmeta-net:
    external: true
