services:
  cognosfm-web:
    build:
      context: .
      args:
        VITE_MODE: develop
        VITE_API_BASE_URL: ""
    ports:
      - "3010:80"
    environment:
      BACKEND_URL: http://172.17.0.1:8087
    restart: unless-stopped
